spring:
  application:
    name: sportsmanager
  datasource:
    url: jdbc:mysql://localhost:3306/sports_manager?createDatabaseIfNotExist=True
    username: root
    password: learnSpring

sportsmanager:
  seeder:
    coaches: 10
    competitors: 100
    competitions: 5